--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingOfTurkey38/MineReset38
build-by-default: true
branches:
- main
- PM5
projects:
  MineReset38:
    path: ""
    icon: icon.png
    libs:
      - src: sof3/await-generator/await-generator
        version: ^3.1.0
      - src: ACM-PocketMine-MP/await-std/await-std
        version: ^0.3.0
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
        branch: PM5
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
    lint:
      phpstan: false
...
